name=str(input("ENTER YOUR NAME"))
gender=input("ENTER YOUR GENDER")
sem=int(input("ENTER YOUR SEMESTER"))
roll_no=int(input("ENTER YOUR ROLL NUMBER"))
attendance=input("ARE YOU PRESENT")
cgpa=float(input("ENTER YOUR CGPA"))
var=None
print("YOUR NAME IS ",name)
print("YOUR GENDER IS ",gender)
print("YOUR SEMESTER IS ",sem)
print("YOUR ROLL NUMBER IS ",roll_no)
print("roll no!!",roll_no,attendance)
print("CGPA:",cgpa)
print(var)
